name: python-rye-install-ubuntu
description: Installs [Rye](rye.astral.sh) on Github Ubuntu Runners.
inputs:
  rye-version:
    description: The version of `Rye` to install
    default: "latest"
runs:
  using: "composite"
  steps:
    - env:
        RYE_VERSION: "${{ inputs.rye-version }}"
        RYE_INSTALL_OPTION: "--yes"
    - run: |
        curl -sSf https://rye.astral.sh/get
        source $HOME/.rye/env
      shell: bash
