name: python-rye-install-ubuntu
description: Installs [Rye](rye.astral.sh) on Github Ubuntu Runners.
inputs:
  rye-version:
    description: The version of `Rye` to install
    default: "latest"
  python-version:
    description: The version of Python to install along with Rye.
    default: "3.12"
runs:
  using: "composite"
  steps:
    - name: Install Rye
      env:
        RYE_VERSION: "${{ inputs.rye-version }}"
        RYE_TOOLCHAIN_VERSION: "${{ inputs.python-version }}"
        RYE_INSTALL_OPTION: "--yes"
      shell: bash
      run: |
        curl -sSf https://rye.astral.sh/get | bash
        echo "source $HOME/.rye/env" >> $HOME/.profile
        source $HOME/.profile
        rye --version
        echo "PATH=$PATH" >> "$GITHUB_ENV"
        echo "RYE_NO_AUTO_INSTALL=1" >> "$GITHUB_ENV"
